/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ClassificationResult = IDL.Record({
  'disposalMethod' : IDL.Text,
  'environmentalTip' : IDL.Text,
  'timestamp' : Time,
  'itemType' : IDL.Text,
  'funFact' : IDL.Text,
  'points' : IDL.Nat,
});
export const UserProfilePublic = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Opt(IDL.Text),
  'scanCount' : IDL.Nat,
  'lastScanTimestamp' : Time,
  'dailyChallengeProgress' : IDL.Nat,
  'scanHistory' : IDL.Vec(ClassificationResult),
  'points' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'classifyItemOffline' : IDL.Func(
      [IDL.Text],
      [ClassificationResult],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfilePublic], [], []),
  'scanItem' : IDL.Func([IDL.Text], [ClassificationResult], []),
  'updateDisplayName' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ClassificationResult = IDL.Record({
    'disposalMethod' : IDL.Text,
    'environmentalTip' : IDL.Text,
    'timestamp' : Time,
    'itemType' : IDL.Text,
    'funFact' : IDL.Text,
    'points' : IDL.Nat,
  });
  const UserProfilePublic = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Opt(IDL.Text),
    'scanCount' : IDL.Nat,
    'lastScanTimestamp' : Time,
    'dailyChallengeProgress' : IDL.Nat,
    'scanHistory' : IDL.Vec(ClassificationResult),
    'points' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'classifyItemOffline' : IDL.Func(
        [IDL.Text],
        [ClassificationResult],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfilePublic], [], []),
    'scanItem' : IDL.Func([IDL.Text], [ClassificationResult], []),
    'updateDisplayName' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };