/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClassificationResult {
  'disposalMethod' : string,
  'environmentalTip' : string,
  'timestamp' : Time,
  'itemType' : string,
  'funFact' : string,
  'points' : bigint,
}
export type Time = bigint;
export interface UserProfilePublic {
  'principal' : Principal,
  'displayName' : [] | [string],
  'scanCount' : bigint,
  'lastScanTimestamp' : Time,
  'dailyChallengeProgress' : bigint,
  'scanHistory' : Array<ClassificationResult>,
  'points' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'classifyItemOffline' : ActorMethod<[string], ClassificationResult>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<[string, bigint]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfilePublic]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfilePublic], undefined>,
  'scanItem' : ActorMethod<[string], ClassificationResult>,
  'updateDisplayName' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];